name: Automated Unit Testing
on:
  pull_request:
  workflow_dispatch:
    inputs: 
      branch: 
        default: 'test-framework'
jobs:
  run-unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout under $GITHUB_WORKSPACE
        uses: actions/checkout@test-framework

      - name: Set up NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 21

      - name: Install all dependencies
        run: npm install

      - name: Run Tests
        run: npm run test
